---
- job:
    name: sanity
    run: .playbooks/sanity.yaml

- project:
    default-branch: main
    gh_check:
      jobs:
        - sanity
    gh_gate:
      jobs:
        - sanity
    gh_post:
      jobs:
        - sanity
    gh_tag:
      jobs:
        - sanity
