---
- job:
    name: sanity
    run: .playbooks/sanity.yaml
    
- job:
    name: build
    run: .playbooks/build.yaml

- job:
    name: postbuild
    run: .playbooks/postbuild.yaml

- project:
    default-branch: main
    gh_check:
      jobs:
        - sanity
    gh_gate:
      jobs:
        - sanity
    gh_post:
      jobs:
        - sanity
        - build
        - postbuild
    gh_tag:
      jobs:
        - sanity
